apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  labels:
    app: {{ .Values.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      containers:
      - name: {{ .Values.Name }}
        image: {{ .Values.ImageName }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
